# wrangler.toml
name = "herbimagecreator"
main = "src/index.js"
compatibility_date = "2024-12-01"

# KV Binding للبيانات النباتية
[[kv_namespaces]]
binding = "PLANT_DB"
id = "01d04fd088e040dea48aef5cad7b9cd3"
